import Zoom from "./images/zoom.webp";


export const productData=[
    {
      img: Zoom,
      new: "NEW",
      num: "20%",
      off: "OFF",
      
      desc: "Cooler Master Compact Home And Business Core i3 Pro Desktop Computer",
      brand:"Cooler Master",
      price: "R 12,999",
      del: "R 13,999",
      location: "JHB",
      location2: "PTA",
      stock: "In stock",
      star:"4.7(71)",
      btn:"View Product"
    },
    {
      img: Zoom,
      new: "NEW",
      num: "20%",
      off: "OFF",
      desc: "Cooler Master Compact Home And Business Core i3 Pro Desktop Computer",
      brand:"Cooler Master",
      price: "R 12,999",
      del: "R 13,999",
      location: "JHB",
      location2: "PTA",
      stock: "In stock",
      star:"4.7(71)",
      btn:"View Product"
    },
    {
      img: Zoom,
      new: "NEW",
      num: "20%",
      off: "OFF",
      desc: "Cooler Master Compact Home And Business Core i3 Pro Desktop Computer",
      brand:"Cooler Master",
      price: "R 12,999",
      del: "R 13,999",
      location: "JHB",
      location2: "PTA",
      stock: "In stock",
      star:"4.7(71)",
      btn:"View Product"
    },
    {
      img: Zoom,
      new: "NEW",
      num: "20%",
      off: "OFF",
      desc: "Cooler Master Compact Home And Business Core i3 Pro Desktop Computer",
      brand:"Cooler Master",
      price: "R 12,999",
      del: "R 13,999",
      location: "JHB",
      location2: "PTA",
      stock: "In stock",
      star:"4.7(71)",
      btn:"View Product"
    },
    {
      img: Zoom,
      new: "NEW",
      num: "20%",
      off: "OFF",
      desc: "Cooler Master Compact Home And Business Core i3 Pro Desktop Computer",
      brand:"Cooler Master",
      price: "R 12,999",
      del: "R 13,999",
      location: "JHB",
      location2: "PTA",
      stock: "In stock",
      star:"4.7(71)",
      btn:"View Product"
    },
    {
      img: Zoom,
      new: "NEW",
      num: "20%",
      off: "OFF",
      desc: "Cooler Master Compact Home And Business Core i3 Pro Desktop Computer",
      brand:"Cooler Master",
      price: "R 12,999",
      del: "R 13,999",
      location: "JHB",
      location2: "PTA",
      stock: "In stock",
      star:"4.7(71)",
      btn:"View Product"
    },
    {
      img: Zoom,
      new: "NEW",
      num: "20%",
      off: "OFF",
      desc: "Cooler Master Compact Home And Business Core i3 Pro Desktop Computer",
      brand:"Cooler Master",
      price: "R 12,999",
      del: "R 13,999",
      location: "JHB",
      location2: "PTA",
      stock: "In stock",
      star:"4.7(71)",
      btn:"View Product"
    },
    {
      img: Zoom,
      new: "NEW",
      num: "20%",
      off: "OFF",
      desc: "Cooler Master Compact Home And Business Core i3 Pro Desktop Computer",
      brand:"Cooler Master",
      price: "R 12,999",
      del: "R 13,999",
      location: "JHB",
      location2: "PTA",
      stock: "In stock",
      star:"4.7(71)",
      btn:"View Product"
    },
    {
      img: Zoom,
      new: "NEW",
      num: "20%",
      off: "OFF",
      desc: "Cooler Master Compact Home And Business Core i3 Pro Desktop Computer",
      brand:"Cooler Master",
      price: "R 12,999",
      del: "R 13,999",
      location: "JHB",
      location2: "PTA",
      stock: "In stock",
      star:"4.7(71)",
      btn:"View Product"
    },
    {
      img: Zoom,
      new: "NEW",
      num: "20%",
      off: "OFF",
      desc: "Cooler Master Compact Home And Business Core i3 Pro Desktop Computer",
      brand:"Cooler Master",
      price: "R 12,999",
      del: "R 13,999",
      location: "JHB",
      location2: "PTA",
      stock: "In stock",
      star:"4.7(71)",
      btn:"View Product"
    },
    {
      img: Zoom,
      new: "NEW",
      num: "20%",
      off: "OFF",
      desc: "Cooler Master Compact Home And Business Core i3 Pro Desktop Computer",
      brand:"Cooler Master",
      price: "R 12,999",
      del: "R 13,999",
      location: "JHB",
      location2: "PTA",
      stock: "In stock",
      star:"4.7(71)",
      btn:"View Product"
    },
    {
      img: Zoom,
      new: "NEW",
      num: "20%",
      off: "OFF",
      desc: "Cooler Master Compact Home And Business Core i3 Pro Desktop Computer",
      brand:"Cooler Master",
      price: "R 12,999",
      del: "R 13,999",
      location: "JHB",
      location2: "PTA",
      stock: "In stock",
      star:"4.7(71)",
      btn:"View Product"
    },
   

]